site_name: Moje projekty
site_author: Radosław Krupa
site_url: https://radoxan.github.io/ds_ai_portfolio/
site_description: >-
    Portfolio moich projektów z Data Science i AI!


repo_name: radoxan/ds_ai_portfolio
repo_url: https://github.com/radoxan/ds_ai_portfolio
theme:
  name: material
  palette:
    primary: green
    accent: green

nav:
- Strona Domowa: index.md
- Obecny projekt:
  - 'ICanHelpU':  ICanHelpU/index.md
- Poprzednie projekty:
  - "BendTime": BendTime/index.md
  - "Iris": Iris/index.md
  - "Titanic": Titanic/index.md