site_name: Moje projekty
site_author: Radosław Krupa
site_url: https://radoxan.github.io/ds_ai_portfolio/
site_description: >-
    Portfolio moich projektów z Data Science i AI!


repo_name: radoxan/ds_ai_portfolio
repo_url: https://github.com/radoxan/ds_ai_portfolio
theme:
  name: material
  palette:
    primary: green
    accent: green

nav:
- O mnie: index.md

- Obecny projekt:
  - 'GeneratorMiniatur': DrawingGen/index.md
- Poprzednie projekty:
  - "Analiza danych":
    - "Iris": Iris/index.md
    - "Titanic": Titanic/index.md
  - "Uczenie maszynowe":
      - "FindFriends": FindFriends/index.md
      - "BendTime": BendTime/index.md
  - "Sztuczna inteligencja":
    - "InvoiceReader": InvoiceReader/index.md
    - "ArtGalleryGenerator": ArtGalleryGenerator/index.md
    - "MyOwnGPT": MyOwnGPT/index.md
  - "Inne":
    - "KonwerterERP": KonwerterERP/index.md